/** @format */

const Products = [
  {
    id: 11,
    name: "Lava",
    price: 400,
    imageURL: "https://i.ibb.co/7NV1dCK/lavafront.jpg",
    imageURLExtra: "https://i.ibb.co/FVN0dRG/lavaback.jpg",
    quantity: 100,
  },
  {
    id: 12,
    name: "Lava",
    price: 700,
    imageURL: "https://i.ibb.co/J5GvsqT/lava250front.jpg",
    imageURLExtra: "https://i.ibb.co/Mgn57gw/lava250back.jpg",
    quantity: 250,
  },
  {
    id: 13,
    name: "Lava",
    price: 1400,
    imageURL: "https://i.ibb.co/fvYmgHk/lava500front.jpg",
    imageURLExtra: "https://i.ibb.co/whWJxgh/lava500back.jpg",
    quantity: 500,
  },
  {
    id: 14,
    name: "Lava",
    price: 2600,
    imageURL: "https://i.ibb.co/wN0NYR5/lava1kgfront.jpg",
    imageURLExtra: "https://i.ibb.co/SxhNHW5/lava1kgback.jpg",
    quantity: 1000,
  },
  {
    id: 15,
    name: "Manorama",
    price: 400,
    imageURL: "https://i.ibb.co/Bwrdy6H/manfront.jpg",
    imageURLExtra: "https://i.ibb.co/5vt86fB/manback.jpg",
    quantity: 100,
  },
  {
    id: 16,
    name: "Manorama",
    price: 700,
    imageURL: "https://i.ibb.co/rG8YHQC/man250front.jpg",
    imageURLExtra: "https://i.ibb.co/WPWnPZn/man250back.jpg",
    quantity: 250,
  },
  {
    id: 17,
    name: "Manorama",
    price: 1400,
    imageURL: "https://i.ibb.co/LNKLvMc/man500front.jpg",
    imageURLExtra: "https://i.ibb.co/cyHT8z9/man500back.jpg",
    quantity: 500,
  },
  {
    id: 18,
    name: "Manorama",
    price: 2600,
    imageURL: "https://i.ibb.co/mTtpks5/man1kgfront.jpg",
    imageURLExtra: "https://i.ibb.co/k9skVsb/man1kgback.jpg",
    quantity: 1000,
  },
  {
    id: 19,
    name: "Madheshwar",
    price: 400,
    imageURL: "https://i.ibb.co/BjsThMr/madhfront.jpg",
    imageURLExtra: "https://i.ibb.co/V3dNXvg/madhback.jpg",
    quantity: 100,
  },
  {
    id: 20,
    name: "Madheshwar",
    price: 700,
    imageURL: "https://i.ibb.co/Vp5sQHd/madh250front.jpg",
    imageURLExtra: "https://i.ibb.co/2gr0WZW/madh250back.jpg",
    quantity: 250,
  },
  {
    id: 21,
    name: "Madheshwar",
    price: 1400,
    imageURL: "https://i.ibb.co/QrhP84y/madh500front.jpg",
    imageURLExtra: "https://i.ibb.co/k2qrFcy/madh500back.jpg",
    quantity: 500,
  },
  {
    id: 22,
    name: "Madheshwar",
    price: 2600,
    imageURL: "https://i.ibb.co/HPyWsQh/madh1lkgfront.jpg",
    imageURLExtra: "https://i.ibb.co/2K1L4w2/madh1kgback.jpg",
    quantity: 1000,
  },

  // {
  //   id: 14,
  //   name: "Lava",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/3kHm2qv/Lava-Front.png",
  // },
  // {
  //   id: 15,
  //   name: "Manorama",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/ccnTBqL/Manorama-Front.png",
  // },
  // {
  //   id: 16,
  //   name: "Madeshwar",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/Wvp26qV/Madeshwar-Front.png",
  // },

  // {
  //   id: 17,
  //   name: "Lava",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/3kHm2qv/Lava-Front.png",
  // },
  // {
  //   id: 18,
  //   name: "Manorama",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/ccnTBqL/Manorama-Front.png",
  // },
  // {
  //   id: 19,
  //   name: "Madeshwar",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/Wvp26qV/Madeshwar-Front.png",
  // },
];

export default Products;
