/** @format */

const Products = [
  {
    id: 11,
    name: "Lava",
    price: 400,
    imageURL: "https://i.ibb.co/sVMF25S/Lav-100-Gm-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/8KtSJGz/Lav-100-Gm-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/tcj2ksh/Lav-100-Gm-Zoom.jpg",
    quantity: 100,
  },
  {
    id: 12,
    name: "Lava",
    price: 700,
    imageURL: "https://i.ibb.co/Jd72Mx1/Lav-250-Gm-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/TvtNms3/Lav-250-Gm-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/ThV39tj/Lav-250-Gm-Zoom.jpg",
    quantity: 250,
  },
  {
    id: 13,
    name: "Lava",
    price: 1400,
    imageURL: "https://i.ibb.co/jTVC0vB/Lav-500-Gm-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/1XVtc1c/Lav-500-Gm-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/rmR7XWD/Lav-500-Gm-Zoom.jpg",
    quantity: 500,
  },
  {
    id: 14,
    name: "Lava",
    price: 2600,
    imageURL: "https://i.ibb.co/jRWkyKX/Lav-1-Kg-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/886Rbwt/Lav-1-Kg-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/8sFsPhF/Lav-1-Kg-Zoom.jpg",
    quantity: 1000,
  },
  {
    id: 15,
    name: "Manorama",
    price: 400,
    imageURL: "https://i.ibb.co/5TDt7LT/Man-100gm-Front-1.jpg",
    imageURLExtra1: "https://i.ibb.co/GcRwbdG/Man-100gm-Back-1.jpg",
    imageURLExtra2: "https://i.ibb.co/519611G/Man-100gm-Zoom.jpg",
    quantity: 100,
  },
  {
    id: 16,
    name: "Manorama",
    price: 700,
    imageURL: "https://i.ibb.co/wQRfXt6/Man-250-Gm-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/bFWvftB/Man-250-Gm-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/R9tSqyN/Man-250-Gm-zoom.jpg",
    quantity: 250,
  },
  {
    id: 17,
    name: "Manorama",
    price: 1400,
    imageURL: "https://i.ibb.co/DgdB20z/Man-500-Gm-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/KWxyD1p/Man-500-Gm-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/X4F6Sjk/Man-500-Gm-Zoom.jpg",
    quantity: 500,
  },
  {
    id: 18,
    name: "Manorama",
    price: 2600,
    imageURL: "https://i.ibb.co/LrmNDSm/Man-1-Kg-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/MZp2ZDJ/Man-1-Kg-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/rmfCGb5/Man-1-Kg-Zoom.jpg",
    quantity: 1000,
  },
  {
    id: 19,
    name: "Madheshwar",
    price: 400,
    imageURL: "https://i.ibb.co/xzC9fYn/Mad-100gm-Front-1.jpg",
    imageURLExtra1: "https://i.ibb.co/1szcS7w/Mad-100gm-Back-1.jpg",
    imageURLExtra2: "https://i.ibb.co/862b93V/Mad-100gm-Zoom-1.jpg",
    quantity: 100,
  },
  {
    id: 20,
    name: "Madheshwar",
    price: 700,
    imageURL: "https://i.ibb.co/tZJ3xpr/Mad-250-Gm-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/YW9mjy1/Mad-250-Gm-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/vhdMNt6/Mad-250-Gm-Zoom.jpg",
    quantity: 250,
  },
  {
    id: 21,
    name: "Madheshwar",
    price: 1400,
    imageURL: "https://i.ibb.co/ZTd8hGS/Mad-500-Gm-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/pzWQ9Cp/Mad-500-Gm-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/DVrqSx7/Mad-500-Gm-Zoom.jpg",
    quantity: 500,
  },
  {
    id: 22,
    name: "Madheshwar",
    price: 2600,
    imageURL: "https://i.ibb.co/sV4xP6V/Mad-1-Kg-Front.jpg",
    imageURLExtra1: "https://i.ibb.co/xSRtvNd/Mad-1-Kg-Back.jpg",
    imageURLExtra2: "https://i.ibb.co/BCNmgmc/Mad-1-Kg-Zoom.jpg",
    quantity: 1000,
  },

  // {
  //   id: 14,
  //   name: "Lava",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/3kHm2qv/Lava-Front.png",
  // },
  // {
  //   id: 15,
  //   name: "Manorama",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/ccnTBqL/Manorama-Front.png",
  // },
  // {
  //   id: 16,
  //   name: "Madeshwar",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/Wvp26qV/Madeshwar-Front.png",
  // },

  // {
  //   id: 17,
  //   name: "Lava",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/3kHm2qv/Lava-Front.png",
  // },
  // {
  //   id: 18,
  //   name: "Manorama",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/ccnTBqL/Manorama-Front.png",
  // },
  // {
  //   id: 19,
  //   name: "Madeshwar",
  //   price: 500,
  //   imageURL: "https://i.ibb.co/Wvp26qV/Madeshwar-Front.png",
  // },
];

export default Products;
